version: '2'
services:
  nginx:
    image: nginx:1-alpine
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
     - ./nginx/common:/usr/share/nginx/html/common
    ports:
     - "7100:7100"
    depends_on:
     - default
     - center
     - side
     - api
     - grpc
     - list
     - proxy

  default:
    build: ./default
    ports:
     - "7101:7101"


