version: '2'
services:
  nginx:
    image: nginx:1-alpine
    container_name: nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
     - ./nginx/common:/usr/share/nginx/html/common
    ports:
     - "80:6200"
    depends_on:
     - default
     - data
     - map
     - information
     - search
     - statistics
     - rabbitmq
     - proxy
    restart: always

  default:
    build: ./default
    container_name: default
    ports:
     - "6201:6201"

  data:
    build: ./services/data
    container_name: data
    ports:
      - "6202:6202"
    restart: always

  map:
    build: ./services/map
    container_name: map
    ports: 
      - "6203:6203"
    restart: always
    environment:
      - QUEUE_NAME=map-statics
      - CONNECTION_URL=amqp://rabbitmq

  information:
    build: ./services/information
    container_name: information
    ports:
     - "6204:6204"
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - QUEUE_NAME=information-statics
      - CONNECTION_URL=amqp://rabbitmq

  search:
    build: ./services/search
    container_name: search
    ports:
     - "6205:6205"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    restart: always
  
  statistics:
    build: ./services/statistics
    container_name: statistics
    ports:
      - "6206:6206"
    depends_on:
      - rabbitmq
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm start'
    restart: always
    environment:
      - QUEUE_STATICS=information-statics
      - MAP_STATICS=map-statics
      - CONNECTION_URL=amqp://rabbitmq:5672

  proxy:
    image: envoyproxy/envoy:v1.15.0
    container_name: proxy
    volumes: 
      - ./grpc-proxy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    network_mode: host
    
