version: '2'
services:
  nginx:
    image: nginx:1-alpine
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
     - ./nginx/common:/usr/share/nginx/html/common
    ports:
     - "6200:6200"
    depends_on:
     - default
     - center
     - side
     - api
     - grpc
     - list
     - proxy

  default:
    build: ./default
    ports:
     - "6201:6201"

  center:
    build: ./left-wc/central-wc
    ports:
     - "6202:6202"
  side:
    build: ./left-wc/side-wc
    ports:
     - "6203:6203"

  api:
    build: ./right-wc/call-api
    environment:
      APIHOST: express-api
      APIPORT: 6210
    ports:
     - "6204:6204"


  grpc:
    build: ./right-wc/call-grpc
    environment:
      GRPCHOST: server-grpc
      GRPCPORT: 6211
    ports:
     - "6205:6205"

  list:
    build: ./right-wc/list-result
    ports:
     - "6206:6206"
  
  proxy:
    image: envoyproxy/envoy:v1.15.0
    volumes: 
      - ./grpc-proxy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    network_mode: host

# docker run -d -v "$(pwd)"/grpc/deploy/envoy.yaml:/etc/envoy/envoy.yaml:ro --network=host envoyproxy/envoy:v1.15.0
  
#  express-api:
#    build: ./api/express
#    ports:
#      - "6210:6210"
#  
#  server-grpc:
#    build: ./api/grpc
#    ports:
#      - "6211:6211"


